<<<<<<< HEAD
language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script: ./vendor/bin/phpunit
=======
#language: php
# php:
#   - 5.4
#   - 5.5
#   - 5.6
#   - hhvm
#
# before_script:
#   - curl -s http://getcomposer.org/installer | php
#   - php composer.phar install --dev
#
# script: ./vendor/bin/phpunit
language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
    # current versions of hhvm do fail one test... see https://github.com/facebook/hhvm/issues/4837
    allow_failures:
        - php: hhvm

before_install:
  # This is mandatory or the 'apt-get install' calls following will fail
  - sudo apt-get update -qq
  - sudo apt-get install -y apache2 libapache2-mod-fastcgi
  - sudo apt-get install -y privoxy

install:
  - composer self-update && composer install

before_script:
  # Disable xdebug for speed.
  # NB: this should NOT be done for hhvm and php 7.0.
  # Also we use the php 5.6 run to generate code coverage reports, and we need xdebug for that
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" -a "$TRAVIS_PHP_VERSION" != "7.0" -a "$TRAVIS_PHP_VERSION" != "5.6" ]; then phpenv config-rm xdebug.ini; fi

  # Set up Apache and Privoxy instances inside the Travis VM and use them for testing against
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then ./tests/ci/travis/setup_php_fpm.sh; ./tests/ci/travis/setup_apache.sh; fi
  - if [ "$TRAVIS_PHP_VERSION" = "hhvm" ]; then ./tests/ci/travis/setup_hhvm.sh; ./tests/ci/travis/setup_apache_hhvm.sh; fi
  - ./tests/ci/travis/setup_privoxy.sh
>>>>>>> design
